import { SitemapUrl, LlmsTxtContent, LlmsTxtRule } from '@/types'

export interface LlmsTxtGenerationOptions {
  siteName?: string
  siteUrl?: string
  description?: string
  includeCredit?: boolean
}

export function generateLlmsTxt(
  urls: SitemapUrl[],
  rules: LlmsTxtRule[] = [],
  options: LlmsTxtGenerationOptions = {}
): LlmsTxtContent {
  const robotsSection = generateRobotsSection(urls, rules, options)
  const jsonSection = generateJsonSection(urls, rules, options)
  const fullContent = `${robotsSection}\n\n${jsonSection}`

  return {
    robotsSection,
    jsonSection,
    fullContent,
  }
}

function generateRobotsSection(
  urls: SitemapUrl[],
  rules: LlmsTxtRule[],
  options: LlmsTxtGenerationOptions
): string {
  let content = '# LLMX v0.2\n'
  content += '# Generated by LLMX for Webflow\n'
  content += '# https://llmx.dev\n\n'

  content += '# Site metadata\n'
  if (options.siteName) {
    content += `Name: ${options.siteName}\n`
  }
  if (options.description) {
    content += `Description: ${options.description}\n`
  }
  content += `Generated: ${new Date().toISOString()}\n\n`

  content += '# Rules\n'
  const includeRules = rules.filter((r) => r.type === 'include')
  const excludeRules = rules.filter((r) => r.type === 'exclude')

  includeRules.forEach((rule) => {
    content += `Allow: ${rule.pattern}\n`
  })

  excludeRules.forEach((rule) => {
    content += `Disallow: ${rule.pattern}\n`
  })

  return content
}

function generateJsonSection(
  urls: SitemapUrl[],
  rules: LlmsTxtRule[],
  options: LlmsTxtGenerationOptions
): string {
  const urlsSortedByPriority = [...urls].sort((a, b) => {
    const priorityA = a.priority || 5
    const priorityB = b.priority || 5
    return priorityB - priorityA
  })

  const topUrls = urlsSortedByPriority.slice(0, 100).map((url) => {
    const matchedRule = rules.find(
      (r) => r.type === 'include' && new RegExp(r.pattern, 'i').test(url.loc)
    )
    return {
      url: url.loc,
      priority: matchedRule?.priority || 5,
      lastmod: url.lastmod,
    }
  })

  const jsonData = {
    version: '0.2',
    site: {
      name: options.siteName || 'Webflow Site',
      url: options.siteUrl || '',
      description: options.description || '',
    },
    pages: topUrls,
    generated_by: 'LLMX for Webflow',
    generated_at: new Date().toISOString(),
  }

  let content = '# Structured data\n'
  content += '```json\n'
  content += JSON.stringify(jsonData, null, 2)
  content += '\n```'

  if (options.includeCredit !== false) {
    content += '\n\n# 🤖 Generated with [LLMX](https://llmx.dev)'
  }

  return content
}

export function validateLlmsTxt(content: string): { isValid: boolean; errors: string[] } {
  const errors: string[] = []
  
  // Check for required sections
  if (!content.includes('# LLMX Generated llms.txt')) {
    errors.push('Missing LLMX header')
  }
  
  if (!content.includes('Allow:')) {
    errors.push('No Allow directives found')
  }
  
  if (!content.includes('<json>')) {
    errors.push('Missing JSON section')
  }
  
  // Check JSON syntax
  const jsonMatch = content.match(/<json>\s*(\{[\s\S]*?\})\s*<\/json>/)
  if (jsonMatch) {
    try {
      JSON.parse(jsonMatch[1])
    } catch (error) {
      errors.push('Invalid JSON syntax in JSON section')
    }
  } else {
    errors.push('JSON section not properly formatted')
  }
  
  return {
    isValid: errors.length === 0,
    errors,
  }
}

export const WEBFLOW_PRESET_RULES: Record<string, LlmsTxtRule[]> = {
  'blog': [
    { type: 'include', pattern: '/blog/', priority: 8, description: 'Include blog posts' },
    { type: 'exclude', pattern: '/blog/tag/', description: 'Exclude tag pages' },
    { type: 'exclude', pattern: '/blog/category/', description: 'Exclude category pages' },
  ],
  'docs': [
    { type: 'include', pattern: '/docs/', priority: 10, description: 'Include documentation' },
    { type: 'include', pattern: '/help/', priority: 9, description: 'Include help center' },
    { type: 'exclude', pattern: '/docs/search', description: 'Exclude search pages' },
  ],
  'products': [
    { type: 'include', pattern: '/products/', priority: 9, description: 'Include product pages' },
    { type: 'include', pattern: '/product/', priority: 9, description: 'Include product detail pages' },
    { type: 'exclude', pattern: '/products/cart', description: 'Exclude cart pages' },
  ],
  'static': [
    { type: 'include', pattern: '/about', priority: 7, description: 'Include about page' },
    { type: 'include', pattern: '/pricing', priority: 10, description: 'Include pricing page' },
    { type: 'include', pattern: '/features', priority: 9, description: 'Include features page' },
    { type: 'include', pattern: '/contact', priority: 6, description: 'Include contact page' },
  ],
}

export const PRESET_RULES = WEBFLOW_PRESET_RULES
